[workspace]
members = [
    "crates/dembly-card",
    "crates/dembly-cli",
    "crates/dembly-core",
    "crates/dembly-docker",
    "crates/dembly-runtime",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
toml = "0.8"

[workspace.package]
version = "0.2.0"
edition = "2021"
license-file = "LICENSE"
publish = false
rust-version = "1.75"
