[package]
name = "dembly-cli"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
rust-version.workspace = true

[[bin]]
name = "dembly"
path = "src/main.rs"

[dependencies]
dembly-card = { path = "../dembly-card" }
dembly-core = { path = "../dembly-core" }
dembly-docker = { path = "../dembly-docker" }
dembly-runtime = { path = "../dembly-runtime" }
